### PR TITLE
Making paths file safe, checking HTTP `get` responses, URL formatting, and comment refactoring

### PR DESCRIPTION
**Pull request by avivweinstein**
Hi Khuyen,

Ive been using your script a little and noticed that there were some bugs with it (when using it out of the box). I fixed parts of your code and want to contribute back to this repository!

Here are some of the changes that I made:

- There was a bug in one of the functions (`get_top_users`) where the code was doing an HTTP get using a malformed URL. This caused the script to error out. The issue was that the URL that was being used to get a user was including the repo we got the user from on the end. I solved this by editing the URL string.
- I added some checks on the HTTP get requests, to check that we are getting a valid HTTP response (response code 200)
- There was also an issue I ran into where the HTTP response packets you would get would be 204. This was happening if you were searching for more pages than were available based on a search term. For instance, if you searched “ML Inference” only 7 pages of results showed up. But if you requested to searched for 10 pages, then you would error out and. break the script.
- There seemed to be a doubling of work/effort when creating .json files. I removed this double/repeat of work.
- I added some code so that the directories and file names that are created are “file safe” (as in, these file paths do not have spaces). When creating directories of save paths, I would replace spaces (“ “) with underscores (“_”)
- Removed the description of each function’s parameters from `scrape_repo` and `scrape_user`. I left a comment instead to let the user read the `PARAMETERS.md` file instead. This cleans up the code a little bit

Let me know if you have any questions about the changes I made or would like me to remove/change some of the edits I made! And if you are ok with it, there are a few future enhancements that Id like to add in!

### CODE REVIEW

**Comment by avivweinstein** [comment]
Let me know if these changes are good with you @khuyentran1401 !

**Comment by avivweinstein** [comment]
Hi @khuyentran1401, have you had a chance to review this?

**Comment by khuyentran1401** [comment]
LGTM, thanks @avivweinstein!

**Comment by axisrow** [comment]
@claude review. Focus on critical issues: bugs, security vulnerabilities, logical errors, data loss risks, performance problems. Do NOT nitpick style, naming conventions, minor formatting, or subjective preferences — only flag issues that could break functionality or cause real harm in production.

**Pull request merged**
